{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "6.8",
      "buildId" : "wzir5wtxwndjlnebphzhobsap4"
    }
  },
  "component" : {
    "group" : "com.github.evrencoskun",
    "module" : "TableView",
    "version" : "v0.8.9.4",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "TableView-v0.8.9.4.aar",
      "url" : "TableView-v0.8.9.4.aar",
      "size" : 104501,
      "sha512" : "d06fb3be452b5d8a5153ec5b1793aff62a41695275e943f6f373aa1b532bdbd881698d11e1c917c763add3ba2ab3624ec8a7ce478426fd28d687a595b0be1bb7",
      "sha256" : "7e89fce878e8544121d6c75c00948440a8e1b0faaf45ca5a21d3210a330454da",
      "sha1" : "0e9d3d8f750a68565246b5571a77c81afbd83d2a",
      "md5" : "9db79d8a1ecf4e90edfd7a30bc9c2f56"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "androidx.annotation",
      "module" : "annotation",
      "version" : {
        "requires" : "1.1.0"
      }
    }, {
      "group" : "androidx.recyclerview",
      "module" : "recyclerview",
      "version" : {
        "requires" : "1.1.0"
      }
    } ],
    "files" : [ {
      "name" : "TableView-v0.8.9.4.aar",
      "url" : "TableView-v0.8.9.4.aar",
      "size" : 104501,
      "sha512" : "d06fb3be452b5d8a5153ec5b1793aff62a41695275e943f6f373aa1b532bdbd881698d11e1c917c763add3ba2ab3624ec8a7ce478426fd28d687a595b0be1bb7",
      "sha256" : "7e89fce878e8544121d6c75c00948440a8e1b0faaf45ca5a21d3210a330454da",
      "sha1" : "0e9d3d8f750a68565246b5571a77c81afbd83d2a",
      "md5" : "9db79d8a1ecf4e90edfd7a30bc9c2f56"
    } ]
  } ]
}